articles = [
  {
    "id": "1",
    "title": "Article1",
    "subtitle": "Article 1 Subtitle",
    "date": "November 8th, 2021",
    "author": "William Shakespeare",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam id diam maecenas ultricies mi eget. Vulputate ut pharetra sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna. Massa sed elementum tempus egestas sed sed. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ac turpis egestas sed tempus urna et. Id velit ut tortor pretium viverra suspendisse potenti. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Commodo sed egestas egestas fringilla. Justo donec enim diam vulputate ut pharetra sit amet. Ac ut consequat semper viverra nam libero justo. Proin gravida hendrerit lectus a. Pharetra et ultrices neque ornare aenean euismod. Aenean pharetra magna ac placerat vestibulum. Quis eleifend quam adipiscing vitae proin sagittis. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Amet consectetur adipiscing elit ut aliquam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Odio facilisis mauris sit amet massa vitae tortor. Consequat nisl vel pretium lectus quam id leo. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Ut aliquam purus sit amet luctus. Sagittis vitae et leo duis ut diam quam nulla. In vitae turpis massa sed elementum tempus egestas. Semper eget duis at tellus at urna condimentum mattis. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget nulla facilisi etiam dignissim diam. In arcu cursus euismod quis viverra. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu feugiat pretium nibh ipsum. Mi in nulla posuere sollicitudin aliquam ultrices. Suscipit tellus mauris a diam. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Sed enim ut sem viverra. Tristique risus nec feugiat in fermentum. Vitae turpis massa sed elementum tempus egestas sed sed. Turpis egestas pretium aenean pharetra magna ac."
  },
  {
    "id": "2",
    "title": "Article2",
    "subtitle": "Article 2 Subtitle",
    "date": "November 8th, 2021",
    "author": "William Shakespeare",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam id diam maecenas ultricies mi eget. Vulputate ut pharetra sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna. Massa sed elementum tempus egestas sed sed. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ac turpis egestas sed tempus urna et. Id velit ut tortor pretium viverra suspendisse potenti. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Commodo sed egestas egestas fringilla. Justo donec enim diam vulputate ut pharetra sit amet. Ac ut consequat semper viverra nam libero justo. Proin gravida hendrerit lectus a. Pharetra et ultrices neque ornare aenean euismod. Aenean pharetra magna ac placerat vestibulum. Quis eleifend quam adipiscing vitae proin sagittis. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Amet consectetur adipiscing elit ut aliquam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Odio facilisis mauris sit amet massa vitae tortor. Consequat nisl vel pretium lectus quam id leo. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Ut aliquam purus sit amet luctus. Sagittis vitae et leo duis ut diam quam nulla. In vitae turpis massa sed elementum tempus egestas. Semper eget duis at tellus at urna condimentum mattis. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget nulla facilisi etiam dignissim diam. In arcu cursus euismod quis viverra. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu feugiat pretium nibh ipsum. Mi in nulla posuere sollicitudin aliquam ultrices. Suscipit tellus mauris a diam. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Sed enim ut sem viverra. Tristique risus nec feugiat in fermentum. Vitae turpis massa sed elementum tempus egestas sed sed. Turpis egestas pretium aenean pharetra magna ac."
  },
  {
    "id": "3",
    "title": "Article3",
    "subtitle": "Article 3 Subtitle",
    "date": "November 8th, 2021",
    "author": "William Shakespeare",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam id diam maecenas ultricies mi eget. Vulputate ut pharetra sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna. Massa sed elementum tempus egestas sed sed. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ac turpis egestas sed tempus urna et. Id velit ut tortor pretium viverra suspendisse potenti. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Commodo sed egestas egestas fringilla. Justo donec enim diam vulputate ut pharetra sit amet. Ac ut consequat semper viverra nam libero justo. Proin gravida hendrerit lectus a. Pharetra et ultrices neque ornare aenean euismod. Aenean pharetra magna ac placerat vestibulum. Quis eleifend quam adipiscing vitae proin sagittis. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Amet consectetur adipiscing elit ut aliquam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Odio facilisis mauris sit amet massa vitae tortor. Consequat nisl vel pretium lectus quam id leo. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Ut aliquam purus sit amet luctus. Sagittis vitae et leo duis ut diam quam nulla. In vitae turpis massa sed elementum tempus egestas. Semper eget duis at tellus at urna condimentum mattis. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget nulla facilisi etiam dignissim diam. In arcu cursus euismod quis viverra. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu feugiat pretium nibh ipsum. Mi in nulla posuere sollicitudin aliquam ultrices. Suscipit tellus mauris a diam. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Sed enim ut sem viverra. Tristique risus nec feugiat in fermentum. Vitae turpis massa sed elementum tempus egestas sed sed. Turpis egestas pretium aenean pharetra magna ac."

  },
  {
    "id": "4",
    "title": "Article4",
    "subtitle": "Article 4 Subtitle",
    "date": "November 8th, 2021",
    "author": "William Shakespeare",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam id diam maecenas ultricies mi eget. Vulputate ut pharetra sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna. Massa sed elementum tempus egestas sed sed. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ac turpis egestas sed tempus urna et. Id velit ut tortor pretium viverra suspendisse potenti. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Commodo sed egestas egestas fringilla. Justo donec enim diam vulputate ut pharetra sit amet. Ac ut consequat semper viverra nam libero justo. Proin gravida hendrerit lectus a. Pharetra et ultrices neque ornare aenean euismod. Aenean pharetra magna ac placerat vestibulum. Quis eleifend quam adipiscing vitae proin sagittis. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Amet consectetur adipiscing elit ut aliquam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Odio facilisis mauris sit amet massa vitae tortor. Consequat nisl vel pretium lectus quam id leo. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Ut aliquam purus sit amet luctus. Sagittis vitae et leo duis ut diam quam nulla. In vitae turpis massa sed elementum tempus egestas. Semper eget duis at tellus at urna condimentum mattis. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget nulla facilisi etiam dignissim diam. In arcu cursus euismod quis viverra. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu feugiat pretium nibh ipsum. Mi in nulla posuere sollicitudin aliquam ultrices. Suscipit tellus mauris a diam. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Sed enim ut sem viverra. Tristique risus nec feugiat in fermentum. Vitae turpis massa sed elementum tempus egestas sed sed. Turpis egestas pretium aenean pharetra magna ac."

  },
  {
    "id": "5",
    "title": "Article5",
    "subtitle": "Article 5 Subtitle",
    "date": "November 8th, 2021",
    "author": "William Shakespeare",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam id diam maecenas ultricies mi eget. Vulputate ut pharetra sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna. Massa sed elementum tempus egestas sed sed. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ac turpis egestas sed tempus urna et. Id velit ut tortor pretium viverra suspendisse potenti. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Commodo sed egestas egestas fringilla. Justo donec enim diam vulputate ut pharetra sit amet. Ac ut consequat semper viverra nam libero justo. Proin gravida hendrerit lectus a. Pharetra et ultrices neque ornare aenean euismod. Aenean pharetra magna ac placerat vestibulum. Quis eleifend quam adipiscing vitae proin sagittis. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Amet consectetur adipiscing elit ut aliquam. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Odio facilisis mauris sit amet massa vitae tortor. Consequat nisl vel pretium lectus quam id leo. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Ut aliquam purus sit amet luctus. Sagittis vitae et leo duis ut diam quam nulla. In vitae turpis massa sed elementum tempus egestas. Semper eget duis at tellus at urna condimentum mattis. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Eget nulla facilisi etiam dignissim diam. In arcu cursus euismod quis viverra. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu feugiat pretium nibh ipsum. Mi in nulla posuere sollicitudin aliquam ultrices. Suscipit tellus mauris a diam. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Sed enim ut sem viverra. Tristique risus nec feugiat in fermentum. Vitae turpis massa sed elementum tempus egestas sed sed. Turpis egestas pretium aenean pharetra magna ac."
  }
]
